name: Build Image using Dockerfile
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v1
        with:
          image: ${{ github.event.repository.name }}
          tag: ${{ github.event.ref }}
          dockerfiles: ./Dockerfile

      - name: Push Github Registry
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ github.event.repository.name }}
          tag: ${{ github.event.ref }}
          registry: ghcr.io
          username: integr8
          password: ${{ secrets.REGISTRY_TOKEN }}
